# Generated by Django 2.2.2 on 2019-06-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='lat',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='marker',
            name='long',
            field=models.FloatField(null=True, verbose_name='latitude'),
        ),
    ]
