# Generated by Django 2.2.2 on 2019-06-18 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
