# Generated by Django 2.2.2 on 2019-06-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='marker',
            name='stat_number',
            field=models.IntegerField(null=True, verbose_name='Station ID'),
        ),
    ]
