# Generated by Django 2.2.2 on 2019-06-19 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_marker_stat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='lat',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='long',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Bus Station Name'),
        ),
        migrations.AlterField(
            model_name='marker',
            name='stat_number',
            field=models.IntegerField(default=0, unique=True, verbose_name='Station ID'),
        ),
    ]
