# Generated by Django 2.2.2 on 2019-06-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20190619_1009'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Marker',
            new_name='BusStop',
        ),
    ]
