# Generated by Django 2.2.2 on 2019-06-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20190619_1014'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test1', models.CharField(max_length=200, verbose_name='test1')),
                ('test2', models.CharField(max_length=200, verbose_name='test2')),
            ],
        ),
    ]
