# Generated by Django 2.2.2 on 2019-06-19 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0009_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
