# Generated by Django 2.2.2 on 2019-06-27 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_delete_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Justification',
            fields=[
                ('DataSource', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Unique Bus Operator Code')),
                ('JustificationID', models.IntegerField(verbose_name='Unique Variation Code')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveTime',
            fields=[
                ('DataSource', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Unique Bus Operator Code')),
                ('DayOfService', models.CharField(max_length=100, verbose_name='Day of service,One day of service could last more than 24 hours')),
                ('TripID', models.CharField(max_length=50, verbose_name='Unique trip code')),
                ('ProgrNumber', models.IntegerField(verbose_name='Sequential position of the stop point in the trip')),
                ('StopPointID', models.CharField(max_length=50, verbose_name='Unique stop point code')),
                ('PlannedTime_Dep', models.IntegerField(verbose_name='Planned departure time from the stop point, in seconds')),
                ('PlannedTime_Arr', models.IntegerField(verbose_name='Planned arrival time at the stop point, in seconds')),
                ('ActualTime_Dep', models.IntegerField(verbose_name='Actual departure time from the stop point, in seconds')),
                ('ActualTime_Arr', models.IntegerField(verbose_name='Actual arrival time at the stop point, in seconds')),
                ('VehicleID', models.CharField(max_length=50, verbose_name='Unique vehicle code arriving at this stop point')),
                ('Passengers', models.IntegerField(verbose_name='Number of passengers on board (previous link)')),
                ('PassengersIn', models.IntegerField(verbose_name='Number of boarded passengers')),
                ('PassengersOut', models.IntegerField(verbose_name='Number of descended passengers')),
                ('Distance', models.IntegerField(verbose_name='Distance measured from the beginning of the trip')),
                ('Suppressed', models.IntegerField(verbose_name='The whole trip has been partially suppressed (0 =achieved, 1 = suppressed)')),
                ('JustificationID', models.IntegerField(verbose_name='Fault code')),
                ('LastUpdate', models.CharField(max_length=100, verbose_name='Time of the last record update')),
                ('Note', models.CharField(max_length=255, verbose_name='Free note')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('routeID', models.IntegerField(primary_key=True, serialize=False, verbose_name='Route ID')),
                ('routeName', models.CharField(max_length=50, verbose_name='Route Name')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingRawData',
            fields=[
                ('DataSource', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Unique Bus Operator Code')),
                ('DayOfService', models.CharField(max_length=100, verbose_name='Day of service,One day of service could last more than 24 hours')),
                ('VehicleID', models.CharField(max_length=50, verbose_name='Unique vehicle code')),
                ('TimePos', models.CharField(max_length=100, verbose_name='Time of the tracking')),
                ('TripID', models.CharField(max_length=50, verbose_name='Unique trip code')),
                ('PosX', models.IntegerField(verbose_name='Longitude')),
                ('PosY', models.IntegerField(verbose_name='Latitude')),
                ('Odometer', models.IntegerField(verbose_name='Odometer of the vehicle')),
                ('TripOdometer', models.IntegerField(verbose_name='Odometer for the trip')),
                ('PassengersIn', models.IntegerField(verbose_name='Number of boarded passengers')),
                ('PassengersOut', models.IntegerField(verbose_name='Number of descended passengers')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('DataSource', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Unique Bus Operator Code')),
                ('DayOfService', models.CharField(max_length=100, verbose_name='Day of service,One day of service could last more than 24 hours')),
                ('TripID', models.CharField(max_length=50, verbose_name='Unique trip code')),
                ('LineID', models.CharField(max_length=50, verbose_name='Unique line code')),
                ('RouteID', models.CharField(max_length=50, verbose_name='Unique route code')),
                ('Direction', models.CharField(max_length=10, verbose_name='Route direction:IB or OB')),
                ('PlannedTime_Dep', models.IntegerField(verbose_name='Planned departure time of the trip, in seconds')),
                ('PlannedTime_Arr', models.IntegerField(verbose_name='Planned arrival time of the trip, in seconds')),
                ('Basin', models.CharField(max_length=50, verbose_name='Basin code')),
                ('TenderLot', models.CharField(max_length=50, verbose_name='Tender lot')),
                ('ActualTime_Dep', models.IntegerField(verbose_name='Actual departure time of the trip, in seconds')),
                ('ActualTime_Arr', models.IntegerField(verbose_name='Actual arrival time of the trip, in seconds')),
                ('Suppressed', models.IntegerField(verbose_name='The whole trip has been suppressed (0 =achieved, 1 = suppressed)')),
                ('JustificationID', models.IntegerField(verbose_name='Fault code')),
                ('LastUpdate', models.CharField(max_length=100, verbose_name='Time of the last record update')),
                ('Note', models.CharField(max_length=255, verbose_name='Free note')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('DataSource', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Unique Bus Operator Code')),
                ('DayOfService', models.CharField(max_length=100, verbose_name='Day of service')),
                ('VehicleID', models.CharField(max_length=50, verbose_name='Unique vehicle code arriving at this stop point')),
                ('Distance', models.IntegerField(verbose_name='Distance travelled by the vehicle in this day')),
                ('Minutes', models.IntegerField(verbose_name='Time worked by the vehicle in the corresponding day')),
                ('LastUpdate', models.CharField(max_length=100, verbose_name='Time of the last record update')),
                ('Note', models.CharField(max_length=255, verbose_name='Free note')),
            ],
        ),
        migrations.RenameField(
            model_name='busstop',
            old_name='long',
            new_name='lng',
        ),
        migrations.RemoveField(
            model_name='busstop',
            name='id',
        ),
        migrations.AlterField(
            model_name='busstop',
            name='stat_number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Station ID'),
        ),
        migrations.CreateModel(
            name='RouteStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.IntegerField(max_length=50, verbose_name='Route Name')),
                ('routeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Routes')),
                ('stopID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.BusStop')),
            ],
        ),
    ]
