# Generated by Django 2.2.2 on 2019-06-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='busstop',
            name='id',
        ),
        migrations.AlterField(
            model_name='busstop',
            name='stat_number',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Station ID'),
        ),
    ]
