# Generated by Django 2.2.2 on 2019-06-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20190627_1351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='busstop',
            old_name='long',
            new_name='lng',
        ),
    ]
