# Generated by Django 2.2.2 on 2019-06-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_auto_20190627_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routestops',
            name='stop_order',
            field=models.IntegerField(verbose_name='Route Name'),
        ),
    ]
