# Generated by Django 2.2.2 on 2019-07-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_auto_20190627_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Justification',
        ),
        migrations.DeleteModel(
            name='LeaveTime',
        ),
        migrations.DeleteModel(
            name='TrackingRawData',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
